### ISSUE TITLE
unlocker not working

### ISSUE THREAD

**Issue by awsomeman1642** [8fn/DLC-Unlocker-PD2#10]
no matter what i do the dlc remain locked i do have other mods installed and i`m not sure if it`s effecting it

**Comment by 8fn** [comment]
Make sure that u dragged the folder `unlock_all_dlcs` inside of the payday2 mods folder, plus i need more info, show screenshot of your mods folder

**Comment by awsomeman1642** [comment]
thanks I had forgotten to do that

**Comment by werter11111111111** [comment]
> Make sure that u dragged the folder `unlock_all_dlcs` inside of the payday2 mods folder, plus i need more info, show screenshot of your mods folder

i did this with the whole folder and that didn't worked so i tried the unlock_all_dlcs file and it still didn't worked, i can use the dlc masks again with another mod but i can't get into my weapon wheel because than the game crashes
