### ISSUE TITLE
Unlock only heists request

### ISSUE THREAD

**Issue by requester11233** [8fn/DLC-Unlocker-PD2#13]
I saw you make the individual character unlocker so if you can make a heist only unlocker too that would be appreciated.

**Comment by ALKOTS** [comment]
Changed this one to suit my needs a while ago, maybe will help you as well https://github.com/ALKOTS/PD2-DLC-Unlocker

**Comment by 8fn** [comment]
> Changed this one to suit my needs a while ago, maybe will help you as well https://github.com/ALKOTS/PD2-DLC-Unlocker

Dont u mind creating a pull request? If u see, we have unlock_all_dlcs folder and unlock_only_characters, if u dont mind, create a pull request with an folder called unlock_only_heists and if it works, i will merge it
