### ISSUE TITLE
How do I install?

### ISSUE THREAD

**Issue by TheHugeFluff** [8fn/DLC-Unlocker-PD2#14]
I'm new top this so how do I install?

**Comment by 8fn** [comment]
You need [superblt](https://superblt.znix.xyz/)
After installing superblt, drag [unlock_all_dlcs](https://github.com/8fn/DLC-Unlocker-PD2/tree/master/unlock_all_dlcs) folder to mods folder at payday2 folder

**Comment by TheHugeFluff** [comment]
I got super blt n beardlib but its not working. If you want to instruct me better you can add me on discord The Cafe Dog#8862
