### ISSUE TITLE
Dlc Unlocker is outdated.

### ISSUE THREAD

**Issue by proksii** [8fn/DLC-Unlocker-PD2#17]
New update makes dlc unlocker outdated

**Comment by PotatoPhantom** [comment]
Replacing the content of dlc-unlocker.lua with the following works for me on Steam.
```
function WinSteamDLCManager:_check_dlc_data(dlc_data)
    return true
end
```

**Comment by edgarcnp** [comment]
> Replacing the content of dlc-unlocker.lua with the following works for me on Steam.
> 
> ```
> function WinSteamDLCManager:_check_dlc_data(dlc_data)
>     return true
> end
> ```

Thank you!

**Comment by M1guelJesus** [comment]
It didn't work for me but I am running Payday on the SteamDeck with proton 8 enabled (the experimental didn't work either)

**Comment by RalseiInABoxuwu** [comment]
Did it work for you guys? I also got 3.3.8, updated beardlip, and got the dlc unlocker folder on my mods folder, but i stil lhave nothing

**Comment by 0Chriss0** [comment]
Did exactly what you describe but still doesnt work

**Comment by RalseiInABoxuwu** [comment]
Ill try it when i get home, thanks a lot!

**Comment by RalseiInABoxuwu** [comment]
> 

I already did it, but i still have everything blocked :c  
![image](https://github.com/8fn/DLC-Unlocker-PD2/assets/136108581/5c3ab1a8-0d3c-4a14-acbe-128716c4d3f0)

**Comment by DSV-YT** [comment]
> Замена содержимого dlc-unlocker.у меня в Steam работает lua со следующим.
> 
> ```
> function WinSteamDLCManager:_check_dlc_data(dlc_data)
>     return true
> end
> ```

is there a command for epic games?

**Comment by M1guelJesus** [comment]
Just replace Steam for Epic:

function WinEpicDLCManager:_check_dlc_data(dlc_data)
    return true
end




This worked for me

**Comment by TheDemonicSurfer** [comment]
What about the characters only version? What do I need to change to get that to work?

**Comment by DSV-YT** [comment]
> 

thank you very much

**Comment by 8fn** [comment]
> Replacing the content of dlc-unlocker.lua with the following works for me on Steam.
> 
> ```
> function WinSteamDLCManager:_check_dlc_data(dlc_data)
>     return true
> end
> ```

Do a pull request and i will merge it

**Comment by 8fn** [comment]
> > 
> 
> I already did it, but i still have everything blocked :c ![image](https://user-images.githubusercontent.com/136108581/244779682-5c3ab1a8-0d3c-4a14-acbe-128716c4d3f0.png)

Did u still have this problem?

**Comment by 8fn** [comment]
> > 
> 
> I already did it, but i still have everything blocked :c ![image](https://user-images.githubusercontent.com/136108581/244779682-5c3ab1a8-0d3c-4a14-acbe-128716c4d3f0.png)

Make sure u only drag the unlock_all_dlcs folder

**Comment by Crashbreaker** [comment]
will this be updated?
