### ISSUE TITLE
Bypass Cheater Kicker dont work

### ISSUE THREAD

**Issue by esteban142536** [8fn/DLC-Unlocker-PD2#3]
I edit the mod.txt, changing the data with the following:

`"name": "noting in particular",
    "description": "There's nothing weir in this txt-JSON file or his lua file",
    "author": "nobody",
    "contact": "NSA",`

But im still be auto kicking when im joining, any help ?

also, could be easy use a .JSON file that a txt ?

**Comment by 8fn** [comment]
> I edit the mod.txt, changing the data with the following:
> 
> `"name": "noting in particular", "description": "There's nothing weir in this txt-JSON file or his lua file", "author": "nobody", "contact": "NSA",`
> 
> But im still be auto kicking when im joining, any help ?
> 
> also, could be easy use a .JSON file that a txt ?

Maybe you are using a build that triggers cheater tag, try to create a new empty default profile and try to join any lobby, if you can join, the problem was not the mod.txt but your previous profile was triggering cheater tag

**Comment by azalty** [comment]
Most DLC items give you the cheater tag. Just host your own games.
