### ISSUE TITLE
Dlcs question

### ISSUE THREAD

**Issue by Dudu30103** [8fn/DLC-Unlocker-PD2#4]
Look, I have the legacy edition, my question is, if I have a dlc and the unlocker gives it to me, will it count as the unlocker gave it to me and will it give me the cheater tag? Or it will come out as if I already had the dlc purchased, I want this for the jacket 😁

**Comment by Dudu30103** [comment]
@8fn

**Comment by azalty** [comment]
If an item is DLC dependant and you don't have the DLC, you'll be marked as cheater.
Else, you shouldn't, even if you have the DLC unlocker enabled.

Just try. If you get kicked from games, you have your reason there. The cheater tag doesn't stay, just close your game and remove the DLC unlocker and it should be gone.

**Comment by 8fn** [comment]
> 

I have legacy edition and i use dlc unlocker. It doesn't give you cheater tag and you can use dlcs from legacy edition with dlc unlocker. No worries

**Comment by 8fn** [comment]
> Look, I have the legacy edition, my question is, if I have a dlc and the unlocker gives it to me, will it count as the unlocker gave it to me and will it give me the cheater tag? Or it will come out as if I already had the dlc purchased, I want this for the jacket 😁

I have legacy edition and i use dlc unlocker. It doesn't give you cheater tag and you can use dlcs from legacy edition with dlc unlocker. No worries
