### ISSUE TITLE
it just don't work

### ISSUE THREAD

**Issue by akii1** [8fn/DLC-Unlocker-PD2#5]
look, i have installed it like guide said, but instead of unlocker and skins i have DOOM SOUNDTRACK WTF

**Comment by akii1** [comment]
i figured out that the "doom soundtrack" is in legendary skins version and "hello world!" is in master version and it's normal but both of them still don't work

**Comment by 8fn** [comment]
Skin unlocker and dlc unlocker are separated mods. Remove your current mod and install first dlc unlocker
[DLC Unlocker](https://github.com/8fn/DLC-Unlocker-PD2/archive/refs/heads/master.zip)

If you want skins unlocker:
[Repository Legendary Skins](https://github.com/8fn/DLC-Unlocker-PD2/tree/legendary-skins)
[Skin Unlocker.LUA](https://raw.githubusercontent.com/8fn/DLC-Unlocker-PD2/legendary-skins/Scripts/Skin%20Unlocker.LUA)

Create a folder in payday2 mods folder named anything you want. Inside of that folder, create a Folder Called Scripts and put the Skin Unlocker.LUA there inside of Scripts Folder

Outside of the Scripts Folder, create a mod.txt
```
{		
    "name" : "EDIT HERE",
    "description" : "EDIT HERE",
    "author" : "EDIT HERE",
    "contact" : "OPTIONAL",
    "version" : "OPTIONAL",
    "persist_scripts" :
    [
        {"global" : "Skin Unlocker", "script_path" : "Scripts/Skin Unlocker.lua"}
    ],
}
```

**Comment by 8fn** [comment]
> i figured out that the "doom soundtrack" is in legendary skins version and "hello world!" is in master version and it's normal but both of them still don't work

"doom soundtrack" and "hello world" its just to bypass cheater kicker, you can edit in mod.txt file

**Comment by 8fn** [comment]
Just drop the folder to mods folder if you want legendary skins
[Legendary Skins](https://github.com/8fn/DLC-Unlocker-PD2/tree/legendary-skins)
