### ISSUE TITLE
DLC Unlocker doesn't work on linux

### ISSUE THREAD

**Issue by femboyfireball** [8fn/DLC-Unlocker-PD2#52]
**Describe the bug**
Title, the fix would likely be simple. Mostly just finding what the right name is. Willing to be the guinea pig for testing.
It also seems to not work with Proton/Wine

**To Reproduce**
1. Download DLC Unlocker
2. Install it
3. Run Payday 2
4. No DLC access

**Expected behavior**
I expected it to give me access to all unowned DLC, like it does on Windows

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 21.3 Cinnamon

**Steam or Epic? (please mark Y (yes)):**
 - Steam: Yes
 - Epic: Likely

**Comment by tskxz** [comment]
Do others mods run on your operating system?

**Comment by femboyfireball** [comment]
Yes, from what I can tell the current setup of SuperBLT for Linux works for everything.
Edit: I should also note that the windows release of SuperBLT works fine with Proton

**Comment by Hp7z** [comment]
Helped me, delete all lines except

`function WINDLCManager:_check_dlc_data(dlc_data)
    return true
end`

in file "dlc-unlocker.lua"

**Comment by tskxz** [comment]
> Helped me, delete all lines except
> 
> `function WINDLCManager:_check_dlc_data(dlc_data) return true end`
> 
> in file "dlc-unlocker.lua"

Thanks for the solution
https://github.com/pd2-stuff/DLC-Unlocker-PD2/tree/linux

**Comment by Mailootje** [comment]
> > Helped me, delete all lines except
> > `function WINDLCManager:_check_dlc_data(dlc_data) return true end`
> > in file "dlc-unlocker.lua"
> 
> Thanks for the solution https://github.com/pd2-stuff/DLC-Unlocker-PD2/tree/linux

Did not work sadly...
