### ISSUE TITLE
Payday 2 Characters only!

### ISSUE THREAD

**Issue by milanheister** [8fn/DLC-Unlocker-PD2#6]
Hello, i have one simple request.
Can you please make same mod but just to unlock characters because i personally dont need everything else and just need characters, to be exact i need scarface only because his dlc is removed. 
So if you can make it only for characters or if you can tell me how to remove everything but characters that would work as well.
Reply to me here or email me: defalt.wd2@gmail.com
Thanks!

**Comment by 8fn** [comment]
> Hello, i have one simple request. Can you please make same mod but just to unlock characters because i personally dont need everything else and just need characters, to be exact i need scarface only because his dlc is removed. So if you can make it only for characters or if you can tell me how to remove everything but characters that would work as well. Reply to me here or email me: [defalt.wd2@gmail.com](mailto:defalt.wd2@gmail.com) Thanks!

Working on that, thanks :+1:

**Comment by 8fn** [comment]
> Hello, i have one simple request. Can you please make same mod but just to unlock characters because i personally dont need everything else and just need characters, to be exact i need scarface only because his dlc is removed. So if you can make it only for characters or if you can tell me how to remove everything but characters that would work as well. Reply to me here or email me: [defalt.wd2@gmail.com](mailto:defalt.wd2@gmail.com) Thanks!

Try it. It unlocks every character except h3h3, i couldn't find the specific name h3h3 dlc at the code, they dont show up.
[unlock_only_characters](https://github.com/8fn/DLC-Unlocker-PD2/tree/master/unlock_only_characters)

**Comment by milanheister** [comment]
I appreciate You thank You very much!

нед, 12. мар 2023. у 20:41 Tanjil ***@***.***> је написао/ла:
